### PR TITLE
Sets FAIcon on UIBarButtonItem selected state

### PR DESCRIPTION
**Pull request by adam-casey**
Before this change when you would press a UIBarButtonItem that had an FAIcon, the icon would switch to a question mark with a box around it for unknown character. 

I just added the titleTextAttributes change for the selected state and now it works how I would expect it to.

### CODE REVIEW

**Comment by patreu22** [comment]
👍  for this PR, also ran into that error :)

**Review by sgelves — APPROVED** [review]
These changes solve the problem. And they're really needed.

**Review by peterforeman — APPROVED** [review]
This indeed fixes the problem. Please merge!

**Comment by felixk** [comment]
.selected is incorrect for the state. 

[Assert] button text attributes only respected for UIControlStateNormal, UIControlStateHighlighted, UIControlStateDisabled and UIControlStateFocused. state = 4 is interpreted as UIControlStateHighlighted.

Should be changed to .highlighted

**Pull request merged**
