### PR TITLE
Updated Font Awesome to 4.6.3 & created crude update tool

### PR DESCRIPTION
**Pull request by othyn**
Tested the new & old to make sure it is all working.

Font Awesome has been updated from 4.4 to 4.6.3.

I've made sure Aliases are included (after initially forgetting) and that the class names have remained the same for the sake of not breaking current installations, although if there is a mismatch - let me know! I could have missed one whilst checking.

The tool is just a simple script I wrote to pull and format the class names and unicode codes to try to make updating a little more painless, take from it what you will. [It uses the YAML data from the official repo](https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml), what they use to generate the FontAwesome icon gallery page, parses and formats the data and just echoes the strings out.

### CODE REVIEW

**Comment by Vaberer** [comment]
Hello Ben,
great idea to write a parser for this library and trying to parse it from their repo. I actually parsed it from the pure html;)

there is just one thing to have it done 100%.  `ViewController.swift` contains a variable `helper`

```
let helper = ["FA500Px", "FAAdjust", "FAAdn"...
```

which holds all names of the icons. So the example app is crashing when you scroll to the bottom.
However, the fastest way how to make an update in the future, is to just print directly three things as a string:

```
case FAGlass, FAMusic, FASearch...
private let FAIcons = ["\u{f000}", "\u{f001}"...
let helper = ["FA500Px", "FAAdjust", "FAAdn"...
```

Would it be possible to print just these 3 parts of the code which would be then substituted with an old values?
Then I can merge it without any problems:)

Best,
Patrik

**Comment by othyn** [comment]
Something like that? :)

Don't know why I put #26, should have been #29...

**Comment by othyn** [comment]
...should be good now, I've tested the example app is working correctly.

**Comment by Vaberer** [comment]
Thanks othyn!

**Pull request merged**
