### PR TITLE
Create UIImage from FontAwesome icon

### PR DESCRIPTION
**Pull request by marekmatula**
Hi 

I made a simple extension of your library. It is based on UIImage support in project:
https://github.com/thii/FontAwesome.swift/blob/master/FontAwesome/FontAwesome.swift

Could you integrate it and release new version, please?

### CODE REVIEW

**Comment by Vaberer** [comment]
Hello Marek,

Thank you very much for the contribution. Idea of creating images is great. I enhanced it a little bit and you can use it a little bit easier now:

```
imageView.setFAIconWithName(FAType.FATwitter, textColor: UIColor.blueColor(), backgroundColor: UIColor.grayColor())
imageView.setFAIconWithName(FAType.FATwitter, textColor: UIColor.blueColor())
```

I hope you will like this little improvement :)

Best,

Patrik

**Comment by marekmatula** [comment]
Great work.

Thanks

**Comment by marekmatula** [comment]
I just updated to version 1.4 with pod command.
I can't see your changes unfortunately.

Could you help me?

**Comment by Vaberer** [comment]
Thanks for testing it. Now, it's fixed. :) try `pod update` and it will work

**Comment by marekmatula** [comment]
It's OK now. 
Thanks!

**Pull request merged**
