### PR TITLE
Added IonIcons font to the project

### PR DESCRIPTION
**Pull request by codytwinton**
The IonIcon font is great: http://ionicons.com

Added code to handle this font

### CODE REVIEW

**Comment by Vaberer** [comment]
Hello Cody,

I am more than glad to see your contribution to Font Awesome Swift.
It's a good idea to add a support for other fonts and symbols but adding extra files with the same code as in an original FAIcon.swift file isn't  the best approach. Further changing the code/fixing bugs will double the work. Once we'd like to add another font, that would not be maintainable at all.

My idea is to extract the bodies of the FA functions 

```
       FontLoader.loadFontIfNeeded()
        let font = UIFont(name: IOStruct.FontName, size: iconSize)
        assert(font != nil, IOStruct.ErrorAnnounce)
        setTitleTextAttributes([NSFontAttributeName: font!], forState: .Normal)
        title = icon.text
```

and create a generic function with a parameter of the font name.

the result would be

```
enum FontType: Int {
    case FontAwesome, IOIcon
}

protocol GenericType { }
extension IOType: GenericType { }
extension FAType: GenericType { }

public extension UIBarButtonItem {

    func setIOIcon(icon: IOType, iconSize: CGFloat) {
        genericSetIcon(.IOIcon, icon: (icon as GenericType), iconSize: iconSize)
    }

    func setFAIcon(icon: FAType, iconSize: CGFloat) {
        genericSetIcon(.FontAwesome, icon: (icon as GenericType), iconSize: iconSize)
    }

    private func genericSetIcon(fontType: FontType, icon: GenericType, iconSize: CGFloat) {
    FontLoader.loadFontIfNeeded()
        let font = UIFont(name: fontType == .IOIcon ? IOStruct.FontName : FAStruct.FontName, size: iconSize)
    setTitleTextAttributes([NSFontAttributeName: font!], forState: .Normal)
    title = (icon as? FAType)?.text ?? (icon as? IOType)?.text
    }
```

Do you agree?

Best,
Patrik

**Comment by codytwinton** [comment]
Totally agree. I'll look into this. For what it's worth, you could probably combine this project with your https://github.com/Vaberer/Google-Material-Design-Icons-Swift project here. Perhaps with a name change?

**Comment by Vaberer** [comment]
Actually, you are right, there is no need to have multiple projects for every type of font. It will be a pretty big break in the library and it might take some time. Right now, I can't promise I can work for it but I am open to any contributions with reusable solutions;)

**Comment by Vaberer** [comment]
I came into a better solution with associated enums

```
enum FontType {
    case FontAwesome(FAType)
    case IOIcon(IOType)
}

func getSymbol(fontType: FontType) -> String? {
    FontLoader.loadFontIfNeeded()
    let symbol: String?
    switch fontType {
    case let .FontAwesome(icon):
        symbol = icon.text
    case let .IOIcon(icon):
        symbol = icon.text
        // ...other fonts
    }
    return symbol
}


func getFont(fontType: FontType, size: CGFloat) -> UIFont? {
    FontLoader.loadFontIfNeeded()
    let fontName: String
    switch fontType {
    case .FontAwesome(_):
        fontName = FAStruct.FontName
    case let .IOIcon(icon):
        fontName = IOStruct.FontName // better solutions is to have just one struct - FontStruct
        // ...other fonts
    }
    return UIFont(name: fontName, size: size)

}

public extension UIBarButtonItem {

    func setIOIcon(icon: IOType, iconSize: CGFloat) {
        genericSetIcon(.IOIcon(.IOSocialGithub), iconSize: iconSize)
    }

    private func genericSetIcon(fontType: FontType, iconSize: CGFloat) {
        let symbol = getSymbol(fontType)
        let font = getFont(fontType, size: iconSize)
        setTitleTextAttributes([NSFontAttributeName: font!], forState: .Normal)
        title = symbol
    }
}
```

**Comment by ranesr** [comment]
@codytwinton @Vaberer I took this idea and built a library which will include different font icons together.

Please check [SwiftIcons](https://github.com/ranesr/SwiftIcons)!

Thank you for all the work you do.

**Comment by Vaberer** [comment]
Great job on your library!

**Comment by codytwinton** [comment]
@ranesr - awesome, man

**Pull request closed without merging**
